version: '3'
services:
  db:
    image: postgres:10
    volumes:
       - db-data:/home/evis/Evis/docker/postgres_sql/data
    ports: 
      - "9003:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  db-data:
