version: '3'
services:
  db:
    container_name: postgres_10_db
    image: postgres:10
    volumes:
      - db-data:/data
    ports:
      - "9005:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  db-data:
